class Strings {
  static const String appTitle = 'ECORIDE';
  static const String signIn = 'Inicia sesión';
  static const String signUp = 'Crea tu cuenta';
  static const String emailAddress = 'Correo electrónico';
  static const String password = 'Contraseña';
  static const String enterBtn = 'Entrar';
  static const String createBtn = 'Crear cuenta';
  static const String dontHaveAccount = '¿No tienes una cuenta?';
  static const String haveAccount = '¿Ya tienes una cuenta?';
  static const String signInLink = 'Inicia sesión';
  static const String fullName = 'Nombre completo';
  static const String phoneNumber = 'Número celular';
  static const String nameError = 'Ingresa un nombre válido';
  static const String phoneError = 'Ingresa un número de celular válido';
  static const String emailError = 'Ingresa un correo electrónico válido';
  static const String passwordLengthError = 'La contraseña debe tener al menos 8 caracteres';
  static const String loadingLogin = 'Entrando...';
  static const String loadingRegister = 'Creando cuenta...';
  static const String genericResponseError = 'Algo salió mal. Intentalo más tarde';
  static const String noInternetConnection = 'No tienes conexión a internet';
  static const String navItem1 = 'Promociones';
  static const String navItem2 = 'Pagos';
  static const String navItem3 = 'Historial de viajes';
  static const String navItem4 = 'Soporte';
  static const String navItem5 = 'Acerca de';
  static const String viewProfile = 'Ver perfil';
  static const String locationDisabled = 'Los servicios de ubicación están deshabilitados';
  static const String locationPermissionDenied = 'Los permisos de ubicación están denegados';
  static const String locationCannotRequest =
      'Los permisos de ubicación están denegados permanentemente, no podemos solicitar permisos';
  static const String panelTitle = 'Bienvenido';
  static const String panelSearchLabel = '¿A dónde quieres ir?';
  static const String panelInputSearchPlaceholder = 'Busca tu destino';
  static const String panelHome = 'Agregar casa';
  static const String panelWork = 'Agregar trabajo';
  static const String panelHomeDefault = 'Dirección de casa';
  static const String panelWorkDefault = 'Dirección de trabajo';
}
